export const INTRODUCTION_TOPICS = [
    'En este post hablamos de tópicos interesantes como:',
    'Los temas interesantes a tratar en este artículo son:',
    'Dentro de los subtemas a tratar en esta entrada tenemos:',
    'A continuación responderemos a preguntas como:',
    'En este artículo sabrás sobre los siguientes temas:',
    'Como temas importantes a tratar en este artículo tenemos:',
    'Vamos a leer en este artículo consultas como:',
    'En los siguientes párrafos podrás leer los siguientes temas:',
    'Las informaciones que conocerás en este artículo serán:',
    'Te ayudaremos a entender explicando los siguientes temas:',
    'Mas abajo usted podra leer sobre los siguientes temas:',
    'En los siguientes tópicos podrá leer informaciones como:',
    'Para responder tus inquietudes con respecto a este contexto, mostraremos los siguientes temas:',
    'Acontinuacion veras contenido como:',
    'Aquí podrás ver tópicos como:',
    'Te escribimos este artículo para conocer los siguientes tópicos:',
    'Para mostrar más en detalle este tema hablaremos de los siguientes subtemas:',
]

export const INTRODUCTION_MOTIVATIONS = [
    'Acompañanos para que te nutras de este conocimiento.',
    'Si estás interesado(a) en saber sobre este tema entonces tienes que leer este artículo.',
    'Tómate unos minutos para responder a tus preguntas.',
    'Dedica un pequeño tiempo para nutrirte estos datos tan interesantes y necesarios.',
    'Si te encuentras interesado o en la necesidad de saber sobre este tópico, entonces estás en el lugar ideal.',
    'Si te causa curiosidad saber sobre esto, entonces no te puedes perder lo que viene.',
    'Si estas aquí es porque estás interesado en saber sobre esta consulta. ¡Acompañanos!',
    'Te invitamos a que descubras tus inquietudes!',
    'Si te interesa y necesitas conocer sobre estos tópicos, entonces continua leyendo más abajo.',
    'Si tu problema está relacionado con estos tópicos, entonces continua leyendo más abajo.',
    'Siguenos en este artículo y te prometemos que tus dudas serán resueltas.',
    'No esperes más, aqui encontraras tus respuestas.',
    'Síguenos en este artículo para que aclares tus dudas.',
    'Siguenos para esta excelente nutrición de contenido.',
    'Tomate unos minutos para que puedas conocer algo nuevo este día.',
    'Te invitamos a que te nutras con nuestro contenido.',
    'Si buscas respuestas sobre este tema, entonces quédate aquí!',
    'Usa unos minutos de tu tiempo y obtendrás los conocimientos requeridos.',
    'Si en verdad te inquieta este tema, pues no dudes en tomarte un tiempo para leer este artículo.',
    'Gaste un poco de su tiempo y siganos en este artículo para aclarar sus dudas.',
]



export const CONCLUSION_COMMENTS_REQUEST = [
    'Si tiene alguna consulta, no dude en dejar su comentario.',
    'Si tiene una pregunta o duda, deje su comentario en la parte de abajo.',
    'En la parte de abajo puedes dejar un comentario en caso de que quieras saber algo mas en particular.',
    'Para consultas u opiniones tenemos la sesión de comentarios.',
    'Para comentario o duda, favor dirigirse a la parte de abajo.',
    'Para alguna inquietud que tengas, puedes dejar tu comentario en la parte de abajo.',
    'Para dudas, sugerencias u opiniones puede escribirnos en la parte de comentarios.',
    'Si después de completar el artículo le queda alguna inquietud, entonces puede dejar su comentario.',
    'Para consultas, favor dirigirse a la sesión de abajo.',
    'Si quieres comentar algo y si tienes alguna duda puedes escribirlo abajo.',
    'Si necesitas alguna aclaración, entonces puedes dejarnos un comentario.',
    'Si tienes alguna duda puedes dejar tu comentario.',
    'Para dudas y comentarios, en la parte de abajo puede escribirnos.',
    'Para recomendaciones o dudas, escríbenos un comentario, ¡te esperamos!',
    'Para aquellas dudas que pueda tener, puede escribirnos un comentario.',
    'Déjanos tu pregunta o comentario y estaremos atentos con tus dudas.',
    'Para inquietudes u opiniones, puedes escribir un comentario.',
    'Para comentarios puedes escribir en la parte de abajo o dejarnos tu opinión.',
    'Si además de todo lo mostrado en este artículo usted quedó con alguna duda, puede dejarnos un comentario.',
]

export const CONCLUSION_FAREWELLS = [
    'Gracias por su atención.',
    'Gracias por visitarnos!',
    'Gracias, su en este sitio presencia es muy importante para nosotros.',
    'Agradecemos su tiempo en nuestra plataforma.',
    'Esperamos que haya sido de ayuda este artículo y agradecemos su presencia.',
    'Estamos contentos con tu presencia, gracias.',
    'Su presencia es importante para nosotros. Muchas gracias.',
    'Estamos agradecidos por tu presencia.',
    'Gracias por su presencia en nuestro blog!',
    '¡Siempre agradecidos con su visita a nuestro sitio!',
    'Agradecidos por su presencia, esperamos haberle ayudado.',
    'Estamos contentos con tu presencia en nuestro blog.',
    'Haber estado con nosotros en nuestro sitio nos pone contentos, gracias.',
    '¡Gracias por preferirnos!',
    'Estamos complacidos con su presencia.',
    'Tu presencia en este sitio nos hace alegres, gracias!',
    'Nuestro sitio web lo estara esperando para cuando quiera volver. Gracias!',
    'Agradecemos tu presencia en nuestro blog!',
    '¡Apreciamos su tiempo en nuestro sitio web!',
    'Esperamos haber ayudado en algo, gracias por su presencia.',
    'Estamos encantados con su presencia en nuestro sitio web.',
]