export enum ArticleState {
    KEYWORD_PLANNING = "KW_PLANNING",
    CONTENT_RESEARCH = "CONT_RESEARCH",
    AI_CONTENT_RESEARCH = "AI_CONT_RESEARCH",
    KEYWORD_TRANSLATE = "KW_TRANSLATE",
    CREATED_IN_WP = "CREATED_IN_WP",
    DRAFT = "DRAFT"
}